linux-yocto-rt %.bbappend: fix running podman failed
Without this commit, running podman failed
...
root@intel-x86-64:~# podman run --tls-verify=false hello-world
✔ docker.io/library/hello-world:latest
Trying to pull docker.io/library/hello-world:latest...
Getting image source signatures
Copying blob 2db29710123e done
Copying config feb5d9fea6 done
Writing manifest to image destination
Storing signatures
bridge: filtering via arp/ip/ip6tables is no longer available by default. Update your scripts to load br_netfilter if you need this.
IPv6: ADDRCONF(NETDEV_CHANGE): veth6f11f564: link becomes ready
IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
cni-podman0: port 1(veth6f11f564) entered blocking state
cni-podman0: port 1(veth6f11f564) entered disabled state
device veth6f11f564 entered promiscuous mode
cni-podman0: port 1(veth6f11f564) entered blocking state
cni-podman0: port 1(veth6f11f564) entered forwarding state
IPv4: martian source 10.88.0.2 from 10.88.0.2, on dev eth0
ll header: 00000000: ff ff ff ff ff ff 8a 2b 79 9f 29 e3 08 06
Error: error attaching to container 7f056504d9115ba6048164efd2c3322bf4514150dd4469c4371891f0409aa593: read unixpacket @->/proc/self/fd/11/attach: read: connection reset by peer
...

This issue is caused the following commits introduced since v5.15.97.
Particularly the top one effectively re-enables CONFIG_MEMCG on
RT kernel.

CONFIG_MEMCG was disabled on purpose to prevent performance degradation
on RT kernel. But then the RT maintainer thought they had fixed the
degradation and re-enabled CONFIG_MEMCG. But that re-enablement triggered
our current issue. There is still no clear connection between the podman
error and these commits. This needs to be further investigated.

RT kernel used to work without CONFIG_MEMCG for a long time and nothing
abnormal has been observed by me after disabling CONFIG_MEMCG.
It would work at least functionally right as before.

  debedeb4264e mm/memcg: Only perform the debug checks on !PREEMPT_RT
  1ef2cd0b8676 mm/memcg: Add a comment regarding the release `obj'.
  f8d153e08d42 mm/memcg: Add missing counter index which are not update in interrupt.
  11624404f67a mm/memcg: Disable migration instead of preemption in drain_all_stock().
  0a1f4de6ed4f mm/memcg: Protect memcg_stock with a local_lock_t
  3f15202f27da mm/memcg: Opencode the inner part of obj_cgroup_uncharge_pages() in drain_obj_stock()
  40dbbd2f9773 mm/memcg: Protect per-CPU counter by disabling preemption on PREEMPT_RT where needed.
  6269831106f5 mm/memcg: Disable threshold event handlers on PREEMPT_RT
  8da0e71b7b7d mm/memcg: Revert ("mm/memcg: optimize user context object stock access")

Issue: LINUXEXEC-25729

Suggested-by: He Zhe <zhe.he@windriver.com>
Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>