Revert "Add bpftool and bpftrace"
This reverts commit 4480465f444dcad0547a8c079b1e59495428d325.

It has build errors:
ERROR: bpftrace-0.16.0 do_configure() failed: Could not find a configuration file for package "LLVM" that is compatible

Check LIN1023-3019 for more info.

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>