networkmanager: move to networking-layer
Issue: LINUXEXEC-24058

Fixes:
  ERROR: No recipes in default available for:
  /build/layers/wrlinux/dynamic-layers/openembedded-layer/recipes-connectivity/networkmanager/networkmanager_%.bbappend

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>