bcc: Enable more kernel debug variables to fix runqlat and other tests
Issue: LIN1023-293 LIN1023-549

bcc regression resulted in many test failures. They were fixed by
configuring the kernel with CONFIG_IKHEADERS.

Executing the bcc script runqlat resulted in the following error:
libbpf: failed to find valid kernel BTF
/virtual/main.c:94:15: error: no member named 'state' in 'struct task_struct'
if (prev->state == TASK_RUNNING) {

This happens for kernels >=5.14, since the value of task_struct changed from
state to __state.
The patch introduces a macro STATE_FIELD which sets to state or __state
depending on the value of CONFIG_DEBUG_INFO_BTF variable.
Use the config fragment: features/debug/debug-btf.scc to enable DEBUG_INFO_BTF.
That fragment also sets enables 4 other kernel debug variables by using
debug-kernel.cfg. Additionally set bitbake KERNEL_DEBUG to true to ensure that
PAHOLE is *not* set to false to ensure that BTF type info is generated and
pahole-native is built.

Signed-off-by: Naveen Gowda <naveen.gowda@windriver.com>