packagefeed-stability: Add MLPREFIX when add depends
Issue: LIN1023-1568

Fixes:
   1, Add below logic to conf/local.conf
      INHERIT += "packagefeed-stability"
   2, bitbake wrlinux-image-small
      ERROR: Nothing PROVIDES 'gcc-cross-i686'. Close matches:
      gcc-cross-x86_64
      lib32-gcc-9-cross-i686
      lib32-gcc-cross-i686
      [snip]
      Missing or unbuildable dependency chain was: ['wrlinux-image-small', 'lib32-meta-extsdk-toolchain', 'gcc-cross-i686']

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>